CC = nvcc
CFLAGS = -O2 -I include

SRC_cuda_bitonic_sort = src/cuda_bitonic_sort.c
OBJ_cuda_bitonic_sort = $(SRC_cuda_bitonic_sort:src/%.c=build/%.o)
BIN_cuda_bitonic_sort = build/cuda_bitonic_sort

# Default Target: Build all binaries
all: $(BIN_cuda_bitonic_sort)

# Rule to Compile Object Files
build/%.o: src/%.c
	mkdir -p build
	$(CC) $(CFLAGS) -c $< -o $@

# Rule to Link Binary
$(BIN_cuda_bitonic_sort): $(OBJ_cuda_bitonic_sort)
	$(CC) $(OBJ_cuda_bitonic_sort) -o $@
	rm -rf build/*.o

# Clean Target
clean:
	rm -rf build
